### ISSUE TITLE
Fade to 0 not working?

### ISSUE THREAD

**Issue by terax111** [spacemanspiff2007/PyArtNet#4]
When i try to fade any channel to 0 it only updates it to 0 after another channel was faded to another value (thats not 0). Setting it to any other value works as intended.

**Comment by spacemanspiff2007** [comment]
Is the channel already at 0? Can you provide a snipped which can reproduce this?

**Comment by terax111** [comment]
import pyartnet
    import asyncio
    import time
    
    node = pyartnet.ArtNetNode('2.100.100.1')
    node.start()
    universe = node.add_universe(8)
    
    
    async def fade_channel(start, value_array, fade_time=0):
        global universe
    
        channel = universe.add_channel(start=start, width=len(value_array))
        channel.add_fade(value_array, fade_time)
        await channel.wait_till_fade_complete()
    
    
    loop = asyncio.get_event_loop()
    print("test1")
    loop.run_until_complete(fade_channel(1, [255]))
    
    time.sleep(1)
    print("test2")
    loop.run_until_complete(fade_channel(1, [0]))

this wont reset channel 1 to 0 instead it will stay at 255 (if you change the last fade to (1,[1]) it will set the channel to 1 without a problem)

i've tested a little bit more since i wrote the issue and found that if i dont add the channel dynamicly (create it as global first and then use it in both fades) it works as intended. So is my first attempt just not an intended usecase?

**Comment by spacemanspiff2007** [comment]
I think this is an issue with you starting the worker when no loop is running.
If you try it like this everything works fine:

```python
import asyncio
import pyartnet

node = pyartnet.ArtNetNode('2.100.100.1')
universe = node.add_universe(8)


async def fade_channel(start, value_array, fade_time=0):
    global universe

    channel = universe.add_channel(start=start, width=len(value_array))
    channel.add_fade(value_array, fade_time)
    await channel.wait_till_fade_complete()
    print(channel.get_channel_values())


async def my_fade():
    node.start()

    await fade_channel(1, [255])
    await asyncio.sleep(1)
    await fade_channel(1, [0])


loop = asyncio.get_event_loop()
loop.run_until_complete(my_fade())
```
```
[255]
[0]
```

**Comment by terax111** [comment]
with that code snippet i still have the same exact issue

**Comment by spacemanspiff2007** [comment]
O_o

Can you try the most recent version I pushed to pypi. Be aware that node.start has to be awaited there
```python
async def my_fade():
    await node.start()

    await fade_channel(1, [255])
    await asyncio.sleep(1)
    await fade_channel(1, [0])


loop = asyncio.get_event_loop()
loop.run_until_complete(my_fade())
```

**Comment by terax111** [comment]
doesnt seem to work, still get the exact same outputs. (hope i testetd it correctly, had to update to python 3.9 as i was using 3.6 for another project)

maybe to clarify: the print(channel.get_channel_values()) gives the intended output ([255] and [0]) but the recieving end of the artnet (in my case tested with two seperate softwares to make sure) get only the 255 signal (and any other thats not 0)

**Comment by spacemanspiff2007** [comment]
Can you please set the logging level to ``logging.DEBUG`` for ``PyArtnet`` and post the log here?
It show exactly what is being sent over UDP.

**Comment by terax111** [comment]
might be a dumb question but how do i do this?

**Comment by spacemanspiff2007** [comment]
just add this to the top:
```python
import logging.handlers
import sys

ch = logging.StreamHandler(sys.stdout)
ch.setLevel(logging.DEBUG)
ch.setFormatter(logging.Formatter("[{asctime:s}] [{name:25s}] {levelname:8s} | {message:s}", style='{'))
logging.getLogger().addHandler(ch)
logging.getLogger().setLevel(logging.DEBUG)
```

But I see now where the problem is:

```python
channel = universe.add_channel(start=start, width=len(value_array))
```

The second time you call this you overwrite the already existing channel.
The new channel value is already off which means the fade to 0 does nothing.

You should probably use ``get_channel`` on the universe so you see if the channel already exists.
And there probably should be an exception if you try to overwrite it.

**Comment by spacemanspiff2007** [comment]
@terax111 
Check out 0.7.0, it will throw an error as expected
